name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
env:
  GVM_DIR: "$HOME/.gvm"

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v3
      
      - name: Install gvm
        shell: bash        
        run: |
          script_content=$(cat ./gvm.sh && echo -e "\ngvm install 1.17.10\n")
          echo $script_content > ~/.bash_profile
          source ~/.bash_profile
        
      - name: Run gvm commands
        shell: bash
        run: gvm install 1.17.10        
        
      - name: Run gvm commands
        shell: bash
        run: gvm use 1.17.10

      - name: Run gvm commands
        shell: bash
        run: gvm info
