name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
 
  build:
    
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3
      
      - name: Install nvm
        shell: bash
        run: |
          curl -o- https://raw.githubusercontent.com/benms/gvm/main/install.sh | tee && echo "gvm install 1.17.10; gvm use 1.17.10;gvm info" | bash        
