name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  GO_INSTALL_VER: "1.17.10"
  GVM_DIR: "$HOME/.gvm"

jobs:

  usage-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        shell: bash
        run: |
          mkdir -p "$GVM_DIR/versions"
          touch "$GVM_DIR/.gvmrc"
          cat ./gvm.sh >> "$HOME/.bash_profile"

      - name: Run usage
        shell: bash
        run: |
          {
            echo -e "gvm install $GO_INSTALL_VER\n"
            echo -e "gvm default $GO_INSTALL_VER\n"
            echo -e "gvm ls\n"
            echo -e "gvm info\n"
            echo -e "gvm rm $GO_INSTALL_VER\n"
          } >> "$HOME/.bash_profile"
          source "$HOME/.bash_profile"

  install-test:

    runs-on: ubuntu-latest

    env:
      INSTALL_URL: "https://raw.githubusercontent.com/benms/gvm/main/install.sh"

    steps:
      - name: Install
        shell: bash
        run: |
          curl -o- $INSTALL_URL | bash
          {
            echo -e "gvm install $GO_INSTALL_VER\n"
            echo -e "gvm default $GO_INSTALL_VER\n"
            echo -e "gvm ls\n"
            echo -e "gvm info\n"
            echo -e "gvm rm $GO_INSTALL_VER\n"
          } >> "$HOME/.bashrc"
          source "$HOME/.bashrc"

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        if: always()
