name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  GVM_DIR: "$HOME/.gvm"
  BASH_PROFILE: "$HOME/.bash_profile"
  GO_INSTALL_VER: "1.17.10"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install p1
        shell: bash
        run: |
          mkdir -p $GVM_DIR
          mkdir -p $GVM_DIR/versions
          touch $GVM_DIR/.gvmrc

      - name: Install p2 and run
        shell: bash
        run: |
          cat ./gvm.sh >> $BASH_PROFILE
          echo -e "\n gvm install $GO_INSTALL_VER\n gvm default $GO_INSTALL_VER\n gvm ls\n gvm info\n gvm rm $GO_INSTALL_VER\n" >> $BASH_PROFILE
          source $BASH_PROFILE
