name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
 
  build:
    
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install gvm
        shell: bash
        run: source ./install.sh
        
      - name: Run gvm commands
        shell: bash
        run: gvm install 1.17.10
        
        
      - name: Run gvm commands
        shell: bash
        run: gvm use 1.17.10

      - name: Run gvm commands
        shell: bash
        run: gvm info
