name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  GVM_DIR: "$HOME/.gvm"
  BASH_PROFILE: "$HOME/.bash_profile"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install p1
        shell: bash
        run: |
          mkdir -p $GVM_DIR
          mkdir -p $GVM_DIR/versions
          touch $GVM_DIR/.gvmrc

      - name: Install p2 and run
        shell: bash
        run: |
          cat ./gvm.sh >> $BASH_PROFILE
          echo -e "\n gvm install 1.17.10\n gvm default 1.17.10\n gvm info\n" >> $BASH_PROFILE
          source $BASH_PROFILE

      # - name: Run gvm commands
      #   shell: bash
      #   run: gvm install 1.17.10

      # - name: Run gvm commands
      #   shell: bash
      #   run: |
      #     gvm use 1.17.10

      # - name: Run gvm commands
      #   shell: bash
      #   run: gvm info
