name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
 
  build:
    
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3
      
      - name: Install nvm
        shell: bash
        run: curl -o- https://raw.githubusercontent.com/benms/gvm/main/install.sh | bash
        
      - name: Reload bash
        shell: bash
        run: source ~/.bashrc

      - name: Install Golang version 1.17.10
        shell: bash
        run: gvm install 1.17.10
        
      - name: set as default 1.17.10
        shell: bash
        run: gvm use 1.17.10
        
      - name: Get go version
        shell: bash
        run: go version
        
      - name: Show list of installed versions
        shell: bash
        run: gvm ls
        
      - name: Show list of installed versions
        shell: bash
        run: gvm info
