name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  GO_INSTALL_VER: "1.17.10"

jobs:

  usage-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        shell: bash
        run: |
          export GVM_DIR="$HOME/.gvm"
          mkdir -p "$GVM_DIR/versions"
          touch $GVM_DIR/.gvmrc
          cat ./gvm.sh >> "$HOME/.bash_profile"

      - name: Run usage
        shell: bash
        run: |
          {
            echo "gvm default $GO_INSTALL_VER"
            echo "========"
            echo "gvm ls"
            echo "========"
            echo "gvm info"
            echo "========"
            echo "gvm rm $GO_INSTALL_VER"
            echo "========"
          } >> "$HOME/.bash_profile"
          source "$HOME/.bash_profile"

  install-test:

    runs-on: ubuntu-latest

    env:
      INSTALL_URL: "https://raw.githubusercontent.com/benms/gvm/main/install.sh"

    steps:
      - name: Install
        shell: bash
        run: |
          curl -o- $INSTALL_URL | bash
          {
            echo "gvm default $GO_INSTALL_VER"
            echo "========"
            echo "gvm ls"
            echo "========"
            echo "gvm info"
            echo "========"
            echo "gvm rm $GO_INSTALL_VER"
            echo "========"
          } >> "$HOME/.bashrc"
          source "$HOME/.bashrc"

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        if: always()
