name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  GVM_DIR: "$HOME/.gvm"
  GVM_VERSIONS: "$GVM_DIR/versions"
  GVM_RC: "$GVM_DIR/.gvmrc"
  BASH_PROFILE: "$HOME/.bash_profile"
  BASH_RC: "$HOME/.bashrc"
  GO_INSTALL_VER: "1.17.10"
  INSTALL_URL: "https://raw.githubusercontent.com/benms/gvm/main/install.sh"

jobs:

  usage-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        shell: bash
        run: |
          mkdir -p $GVM_VERSIONS
          touch $GVM_RC
          cat ./gvm.sh >> $BASH_PROFILE

      - name: Run usage
        shell: bash
        run: |
          {
            echo "gvm default $GO_INSTALL_VER"
            echo "========"
            echo "gvm ls"
            echo "========"
            echo "gvm info"
            echo "========"
            echo "gvm rm $GO_INSTALL_VER"
            echo "========"
          } >> "$BASH_PROFILE"
          source $BASH_PROFILE

  install-test:

    runs-on: ubuntu-latest

    steps:
      - name: Install
        shell: bash
        run: |
          curl -o- $INSTALL_URL | bash
          {
            echo "gvm default $GO_INSTALL_VER"
            echo "========"
            echo "gvm ls"
            echo "========"
            echo "gvm info"
            echo "========"
            echo "gvm rm $GO_INSTALL_VER"
            echo "========"
          } >> "$BASH_RC"
          source $BASH_RC

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        if: always()
