name: Test


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  GVM_DIR: "$HOME/.gvm"
  BASH_PROFILE: "$HOME/.bash_profile"
  GO_INSTALL_VER: "1.17.10"

jobs:

  usage-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Install
        shell: bash
        run: |
          mkdir -p $GVM_DIR
          mkdir -p $GVM_DIR/versions
          touch $GVM_DIR/.gvmrc
          cat ./gvm.sh >> $BASH_PROFILE

      - name: Run usage
        shell: bash
        run: |
          echo -e "\n gvm install $GO_INSTALL_VER\n gvm default $GO_INSTALL_VER\n gvm ls\n gvm info\n gvm rm $GO_INSTALL_VER\n" >> $BASH_PROFILE
          source $BASH_PROFILE

  install-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        shell: bash
        run: |
          curl -o- https://raw.githubusercontent.com/benms/gvm/main/install.sh | bash && . ~/.bashrc

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
